import React, { useEffect, useState } from "react";
import ReactDOM from "react-dom";

import "./styles.css";

const accessToken =
    "BQCNGyp7GihxxNC-WBk7YRmpcCZtTWK7Z-0zlvYFdpOVbICyJOiCF4IW7x0TtWWLTGkgooPgoxWabX5vuemMYDICFEuIMeLMW8YSbgkkEP08JNQLSf21BF4XUhzmcegh7IkXz-XGAWTBHCk71oDTvfgD";

function App() {
    // declaring variable and state for the search query, default set to 'kanye'
    const [query, setQuery] = useState("kanye");
    // declaring variable and state for the albums data response, default set to empty array
    const [albums, setAlbums] = useState([]);
    // useEffect() allows us to run code when React updates the DOM, in this case running fetchAlbum()
    useEffect(() => {
        fetchAlbum();
    }, []);
    // declaring function fetchAlbum to fetch and deal with data
    function fetchAlbum() {
        // declaring variable 'url' using a template literal(backtips) so that we can pass in a variable
        let url = `https://api.spotify.com/v1/search?q=${query}&type=album`;
        // using the fetch function to fetch the url and pass through headers using the access token generated by spotify
        fetch(url, {
            // headers to pass authorization, passing through an access token
            headers: {
                "Content-Type": "application/json",
                Authorization: `Bearer ${accessToken}`
            }
        })
            // promise attached to fetch to parse the response into JSON format
            .then(resp => resp.json())
            // taking the data from the fetch and setting the state for albums to data.albums.items (found from reviewing the JSON data and determining what we needed)
            .then(data => setAlbums(data.albums.items));
    }
    // function to prevent form submission from refreshing the page
    function handleSumbit(e) {
        e.preventDefault();
        // running function fetchAlbum on submission of form
        fetchAlbum();
    }
    // html return that will display 
    return (
        <div className="min-h-screen bg-teal-300 px-10 flex justify-center items-center flex-col">
            <h1 className="text-5xl mb-5">Search Spotify Albums!</h1>
            <h3 className="text-3xl mb-5">Use the search box below to search for albums on Spotify!</h3>
            {/* Search Box */}
            <form className="mb-10 flex" onSubmit={handleSumbit}>
                <input
                    type="text"
                    className="p-2 rounded shadow-lg w-full mr-2"
                    value={query}
                    onChange={e => setQuery(e.target.value)}
                />
                <button className="bg-green-600 text-green-100 py-2 px-4 rounded shadow-lg">
                    Search
        </button>
            </form>

            {/* Show Search Results */}
            <div className="flex flex-wrap">
                {albums.map((album, index) => {
                    const img = album.images[0];
                    const imgUrl = img ? img.url : "https://placekitten.com/g/200/200";

                    return (
                        <div className="mb-10 w-1/3 text-center p-3" key={index}>
                            <img
                                className="rounded mb-3 mx-auto"
                                src={imgUrl}
                                alt={album.name}
                                width="200"
                            />

                            <h3>{album.name}</h3>
                        </div>
                    );
                })}
            </div>
        </div>
    );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
